### ISSUE TITLE
[feat] own socket-timeout for EvaSys Soap-Calls

### ISSUE THREAD

**Issue by crosscodr** [data-quest/EvasysPlugin#28]
SOAP-Calls zu Evasys können sehr lang dauern; z.B. wenn viele Veranstaltungen auf einmal zu Evasys übertragen werden.
Um nicht den globalen default_socket_timeout anheben zu müssen, ist eine eigene Einstellung für das EvaSys-Plugin hilfreich.

**Comment by Krassmus** [comment]
Wieso hast Du das Lebel unreleased weggenommen? Auf dem Pluginmarktplatz ist ja (noch) keine Version mit dieser Änderung. Aus meiner Sicht müsste das bestehen bleiben, bis ich eine neue Version auf den Pluginmarktplatz hochlade, was ich aber bald machen möchte.

**Comment by crosscodr** [comment]
Ah okay, tut mir leid. Ich hab das glaube ich weg genommen, weil es mittlerweile einen Tag für eine Version gab wo dieses Feature drin ist. Jetzt weiß ich Bescheid, dass es sich auf die Veröffentlichung im Pluginmarktplatz bezieht.

**Comment by Krassmus** [comment]
Kein Problem.
