### ISSUE TITLE
Evasys-Plugin in Einrichtungen unterbinden

### ISSUE THREAD

**Issue by Krassmus** [data-quest/EvasysPlugin#35]
Aktuell kann das Evasys noch in Einrichtungen aktiviert sein. Das ergibt aber alleine deswegen schon keinen Sinn, weil man für Einrichtungen keine Daten nach EvaSys übertragen kann. Dies soll einfach deaktiviert werden.

**Comment by crosscodr** [comment]
Moin @Krassmus,
Hab den letzten commit mal bei uns getestet. Das allein scheint leider noch nicht auszureichen.
Habe eine beliebige Einrichtung  bei uns rausgesucht. Beim Menüpunkt "Übersicht" steht in der URL `dispatch.php/insitute...`. Wenn man dann auf "Verwaltung" klickt wird `dispatch.php/course...` aufgerufen. Dort findet sich dann auch der Punkt "Lehrveranst.-Evaluation", der dann beim klicken zum Fehler führt, den Philipp reported hatte.

Ist vielleicht auch ein generell Studip-Problem.

fyi: @schuettloeffel-elsa

**Comment by Krassmus** [comment]
Guter Punkt! Jetzt müsste das behoben sein, oder?

**Comment by crosscodr** [comment]
Jap, ist weg :)

**Comment by Krassmus** [comment]
Super! Danke auch!
